=== lililala223322/631Verify/[公开] CPM_2.2_20260828181403_生成工具/CPM_2.2_20260828181403/xsd/CoreOS.xsd
<?xml version="1.0" encoding="US-ASCII"?>
<xs:schema xmlns:vp="http://www.actri.avic/XMLSchema/VP/1.0" xmlns="http://www.actri.avic/ConfigRecord" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.actri.avic/ConfigRecord" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="TypeLib.xsd"/>
	<xs:element name="CoreOSDescription" type="CoreOSDescriptionType"/>
	<xs:complexType name="KERNEL_MEM_POOL">
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="KERNEL_CONFIG_RECORD_POOL">
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="KERNEL_PG_POOL">
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="KERNEL_POOL">
		<xs:attribute name="PoolName" type="NameType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="WriteProtected" type="booleanType" use="required"/>
	</xs:complexType>
	<xs:complexType name="PORT_POOL">
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="HMLOG_POOL">
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="RAM_PAYLOAD_POOL">
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="ACE_MEM_POOL">
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="KERNEL_IO_REGION_TYPE">
		<xs:attribute name="PoolName" type="NameType" use="required"/>
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="VirtualAddress" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="CachePolicy" type="CachePolicyType" use="optional"/>
	</xs:complexType>
	<xs:complexType name="SHARED_IO_REGION_TYPE">
		<xs:attribute name="PoolName" type="xs:string" use="required"/>
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="VirtualAddress" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="CachePolicy" type="CachePolicyType" use="optional"/>
	</xs:complexType>
	<xs:complexType name="MEMORY_POOL">
		<xs:attribute name="Name" type="NameType" use="required"/>
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="USER_MEMORY_POOL">
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="LIB_POOL">
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="RAM_REGION_TYPE">
		<xs:sequence>
			<xs:element name="kernelMemoryRegion" type="KERNEL_MEM_POOL"/>
			<xs:element name="kernelConfigRecordRegion" type="KERNEL_CONFIG_RECORD_POOL"/>
			<xs:element name="kernelPgPool" type="KERNEL_PG_POOL" minOccurs="0"/>
			<xs:element name="portRegion" type="PORT_POOL">
				<xs:annotation>
					<xs:appinfo/>
				</xs:annotation>
			</xs:element>
			<xs:element name="hmLogRegion" type="HMLOG_POOL"/>
			<xs:element name="kernelRegion" type="KERNEL_POOL" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ramPayloadRegion" type="RAM_PAYLOAD_POOL" minOccurs="0"/>
			<xs:element name="libRegion" type="LIB_POOL"/>
			<xs:element name="userConfigRecordRegion" type="MEMORY_POOL" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="FLASH_REGION_TYPE">
		<xs:attribute name="Base_Address" type="DecOrHexValueType" use="required"/>
		<xs:attribute name="Size" type="DecOrHexValueType" use="required"/>
	</xs:complexType>
	<xs:complexType name="HARDWARE_REGION_TYPE">
		<xs:sequence>
			<xs:element name="PhysicalMemory" type="RAM_REGION_TYPE"/>
			<xs:element name="userMemoryRegion" type="USER_MEMORY_POOL" />
			<xs:element name="kernelIO" type="KERNEL_IO_REGION_TYPE" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="sharedIO" type="SHARED_IO_REGION_TYPE" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="payloadMemory" type="FLASH_REGION_TYPE" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CoreOSDescriptionType">
		<xs:annotation>
			<xs:documentation>Information used to rebuild and configure the CoreOS. this includes the Kernel, BSP and Drivers.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="KernelConfiguration">
				<xs:annotation>
					<xs:documentation>Kernel configuration parameters</xs:documentation>
					<xs:appinfo/>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="partitionSpaceSize" type="DecOrHexValueType" use="optional"/>
					<xs:attribute name="payloadMapSize" type="DecOrHexValueType" use="optional">
						<xs:annotation>
							<xs:documentation>Default=0x20000</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="sysClkRateHz" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default=0xFFFFFFFF</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="unsafeMethodTimeout" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default=0</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="memoryAllocationDisabled" type="booleanType" use="required">
						<xs:annotation>
							<xs:documentation>Default=false</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="watchDogTimerDuration" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default=0</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="kernelVirtualAddress" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default= 0x00100000 (base virtual address for kernel)</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="partitionVirtualAddress" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default = 0x04000000 (base virtual address for all partitions)</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="addressSpaceSize" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default = 0xFFFFFFFF (virutal address space size</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="addressSpaceRegionAllocationUnit" type="DecOrHexValueType" use="required">
						<xs:annotation>
							<xs:documentation>Default = 0x10000000 (max virtual adddress to be allocated)</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="user1" type="DecOrHexValueType" use="optional">
						<xs:annotation>
							<xs:documentation>Default=0</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="user2" type="DecOrHexValueType" use="optional">
						<xs:annotation>
							<xs:documentation>Default=0</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:anyAttribute namespace="##any"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="MemorySize">
				<xs:annotation>
					<xs:appinfo/>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="MemorySizeBss" type="DecOrHexValueType" use="required"/>
					<xs:attribute name="MemorySizeText" type="DecOrHexValueType" use="required"/>
					<xs:attribute name="MemorySizeData" type="DecOrHexValueType" use="required"/>
					<xs:attribute name="MemorySizeRoData" type="DecOrHexValueType" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="HardwareConfiguration" type="HARDWARE_REGION_TYPE"/>
		</xs:sequence>
		<xs:attribute name="KernelName" type="NameType" use="required"/>
		<xs:attribute name="CRC32" type="HexValueType" use="optional"/>
	</xs:complexType>
</xs:schema>

=== lililala223322/631Verify/CPM_L1(原始数据)/coreOS.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CoreOSDescription xmlns="http://www.actri.avic/ConfigRecord" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" KernelName="os" xsi:schemaLocation="http://www.actri.avic/ConfigRecord ../../.xsd/CoreOS.xsd" CRC32="0x1D59760C">
	<KernelConfiguration user1="0x1000" user2="0x1000" payloadMapSize="0x100000" partitionSpaceSize="0x3300000" addressSpaceRegionAllocationUnit="0x1000" addressSpaceSize="0x0" kernelVirtualAddress="0x82000000" memoryAllocationDisabled="false" partitionVirtualAddress="0x70000000" sysClkRateHz="1000" unsafeMethodTimeout="500000000" watchDogTimerDuration="0"/>
	<MemorySize MemorySizeBss="0x0010000" MemorySizeData="0x00010000" MemorySizeRoData="0x0018000" MemorySizeText="0x000b0000"/>
	<HardwareConfiguration>
		<PhysicalMemory Base_Address="0x82000000" Size="0x14000000">
			
			<kernelConfigRecordRegion Size="0x100000"/>
			<kernelMemoryRegion Size="0x100000"/>
			<kernelPgPool Size="0x400000"/>
			<portRegion Size="0x900000"/>
			<kernelRegion Size="0x1000000" WriteProtected="true" PoolName="SMC_MEM_3"/>
			<kernelRegion Size="0x1000000" WriteProtected="false" PoolName="SMC_MEM_4"/>
			<hmLogRegion Size="0x100000"/>
			<ramPayloadRegion Base_Address="0x85000000" Size="0xFB00000"/>
			<libRegion Base_Address="0x95F00000" Size="0x100000"/>
			<!--<userConfigRecordRegion Name="configRecord" Base_Address="0x15F00000" Size="0x100000"/>-->
		</PhysicalMemory>
		<userMemoryRegion Base_Address="0x34000000" Size="0x9000000"/>
		<kernelIO Base_Address="0x0" CachePolicy="IO" PoolName="SMC_MEM_1" Size="0x1000000" VirtualAddress="0x0"/>
		<kernelIO Base_Address="0x20000000" CachePolicy="IO" PoolName="NVRAM" Size="0x80000" VirtualAddress="0x20000000"/>
		<kernelIO Base_Address="0x20100000" CachePolicy="IO" PoolName="REG_SPACE" Size="0x200000" VirtualAddress="0x20100000"/>
		<kernelIO Base_Address="0x21000000" CachePolicy="IO" PoolName="SRAM_MEM" Size="0x80000" VirtualAddress="0x21000000"/>
		<kernelIO Base_Address="0x28000000" CachePolicy="IO" PoolName="CORE_PLIC" Size="0x8000000" VirtualAddress="0x28000000"/>
		<kernelIO Base_Address="0x30000000" CachePolicy="IO" PoolName="A664_BUFFER" Size="0x4000000" VirtualAddress="0x30000000"/>
		<kernelIO Base_Address="0x10000000" CachePolicy="IO" PoolName="SMC_MEM_2" Size="0x1000000" VirtualAddress="0x10000000"/>
		<payloadMemory Base_Address="0x01032000" Size="0x9600000"/>
		<sharedIO Base_Address="0x2000000" CachePolicy="IO" PoolName="sharedIO" Size="0x8000" VirtualAddress="0x20000000"/>
	</HardwareConfiguration>
</CoreOSDescription>
